### ISSUE TITLE
210928 Sprint Day1 : To-Do-List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#1]
- [x] : 주제 정하기
- [x] : 공유 채널 정하기
- [x] : EDA Process 
- [x] : 모임 방식 : 오프라인/ 온라인
  - 오프라인 (SSCA)가능 일자
  - 9/30(목요일)
  - 10/5(화요일)
- [x] : 팀원 역량 소개하기 (R&R)
- [x] : 프로젝트 팀원 목표
- [x]  : 프로젝트 기간 미팅 가능 일정 확인하기

**Comment by seungjaepack** [comment]
1. 모임 방식
- 오늘 진행 내용 확인 후 프로젝트 진척 상태 확인 후 최종 결정
- 9월 30일(목요일) 오프라인으로 진행

**Comment by seungjaepack** [comment]
2. 공유 채널 정하기
- GIT-HUB 에서 공유
- 코드는 develop에서 공유하여 fetch후 main으로 merge
- 회의 내용은 doc folder에 업로드 develop에서 공유

**Comment by dahee-diana96** [comment]
EDA에 대한 위키피디아 페이지:
https://en.wikipedia.org/wiki/Exploratory_data_analysis

**Comment by taeyang1224** [comment]
- 공공데이터포탈 사이트 
https://www.data.go.kr/index.do
- 서울 열린 데이터 포탈 사이트
https://www.seoul.go.kr/main/index.jsp

**Comment by seungjaepack** [comment]
- 오늘 할 것  : 
1. EDA 논문을 읽고 주제 정하기 (기간 : 9월 29일 오전 9시까지)
 - 주제는 논문과 같아도 되고 조금 방향이 다르되 너무 광의 하지 않는 주제 
 - 다른 논문을 찾아보고 팀원들에게 공유
2.  주제를 가지고 EDA를 진행할때 스텝별 과정 및 일정 생각 해보기
Step1: Setting Topic and Direction
Step2: Selecting methods data collection (Crawling or using DB from DB website)
Step3: Processing Data
Step4: Visualization
Step5 : EDA
3.  프로젝트 git reposit 채널에 EDA 진행한 프로세스를 어떻게 이력을 체계적으로 남길지 생각해 보기
4.  자료는 영문을 우선으로 하며 시각화 시킬 수 있는 다양한 방법 구상해보기 (예) 히트 맵, 페어 그래프, 파이그래프, 바그래프)

**Comment by seungjaepack** [comment]
- 프로젝트 기간 팀원 미팅 가능 일정 확인
- 김다희님 :  미팅 참여 불가 (토요일 오전/ 일요일)

**Comment by dahee-diana96** [comment]
이런 진행방식도 있다는 참고자료로 스윽 보셔두 괜찮을 것 같아 공유드립니다!

- https://www.kaggle.com/admond1994/e-commerce-data-eda
- https://towardsdatascience.com/exploratory-data-analysis-on-e-commerce-data-be24c72b32b2

**Comment by seungjaepack** [comment]
- 데이터 포털 
-1. 금융 데이터 포털 (일반데이터 > 무료 선택, 로그인 필요)
https://www.findatamall.or.kr/fsec/dataProd/generalDataProdDetail.do?cmnx=44&goods_id=45c89df4-c29f-11eb-9f58-f220ef21bb88

**Comment by taeyang1224** [comment]
1. TV홈쇼핑과 온라인쇼핑의 비교
https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002748436

2. 온라인쇼핑몰에서 온라인몰의 상품군별 거래액 동향과 동조화 현상
https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002686167

3. 국내 온라인 쇼핑 유형 및 경쟁 분석 - 네이버쇼핑을 중심으로
https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002453801

아무래도 이미짜여진 논문으로 시작하는것이 흐름 잡는데 수월할거같아서 논문위주로 주제를 선정해봤습니다 ! 
다만, 첫번째 주제와 두번째 주제는 데이터 수집 과정에서 어려운점이 많을것 같네요...
두번째 주제와 세번째 주제는 코로나와 연관 지어서 함께 분석을 해도 괜찮을것 같다는 생각이 듭니다. 공공데이터포털에 코로나 관련하여 데이터가 많이 있더라구요 ! 
시간 괜찮으실때 논문 참고해보셔도 좋을것 같습니다 !

**Comment by seungjaepack** [comment]
1. EDA 방향 :  상품 군 별 온라인 쇼핑 거래액을 통해 쇼핑 동향을 파악 (2017~2021)
2. 자료 수집 :  데이터 포털 data set(xls) 또는 데이터랩 API를 통한 데이터 수집 
- 데이터 셋에 대한 내용은 슬렉으로 공유

**Comment by dahee-diana96** [comment]
https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1KE10071&conn_path=I2&language=kr

승재님께서 말씀하신 '상품군 별 온라인 쇼핑 거래액'과 관련하여 활용하기 괜찮을 데이터를 발견한 것 같아 공유드립니다!
