### ISSUE TITLE
10/02 Sprint day 5 : To-Do-List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#10]
- [x]  Sprint Day 4 Review

- Review1
1. 연령대별 쇼핑 트랜드 조회수와 코로나 확진자수 상관관계 확인(인터넷(PC)))
2. 시각화  리뷰 정리
3. 가설 3 - 가설 4 비교
4. 결측치 발생 컬럼 확인하기

- Review 2
Check Sprint system : 이슈 레포트, 스프린트 작업 상태 확인

- Reveiw 3
Source 정리 : 가설 섹션 별 커맨트, 시각화 정리하기 

---------------------------------------------------------------------------------------------------------------------------------
 

-  Splint Day 5 : 1. Daily job Split

- [x] 1. 코드 정리 레포트를 세분화-> 정리 -> 레포트 템플렛 만들기

- [x] 2. 가설 검증은 세분화 하여 테이블 정리 및 시각화 정리 (그룹 활동)

 1)  현재 만들어낸 모델링을 다양하게 표현 (테이블, 그래프)
   a) 기초 통계량 확인 해보기
 -  기초 통계량 확인해보기 (df.describe (include = 'all'))
 -  데이터 개수 확인(count)
 -  각 열의 고유값 개수 : Value_counts()
 b) 여러 그래프로 표현해 보기
 -  그래프와 테이블 장점을 활용: 
 - 1. 상관관계를 쉽게 파악할 수 있는 그래프 
 c) 특징적인 수치 도표화
 - 거래액 상위 / 하위 3개 증감
 - 예) 거래액의 차이를 그래프로 시각화 한 것을 실제 코로나 전후에 얼마나 차이가 나는지 증감률을 그래프 뿐만 아니라
테이블로 정리해 ~%로 증가 했다는 것을 확인할 수 있게 정리 (모든 요소들을 정리하지 않고 중요 부분만 key 정리하기)

- [x] 3. 생각해 보기 : 

1) EDA란 무엇이고 EDA는 프로젝트에 어느 단계에 하는가?
2) 자료 정리 방법
 - 검증 방법을 정량적 분석, 상관관계 분석, 정성적 분석으로 세분화 하고 가설 섹션에 하위 검증 3개 카테고리로
 나눠서 자료 정리

- [x] 4. 인트로에 대한 설명 (전제)을 작성하고 관련 논문 찾아서 ref 추가 하기 

- [x] Splint Day 5 : 2. 향후 작업 내용과 작업 내용 생각해 보기
- 10월 4일 작업 미션: EDA Final Report 70%로 완성
- 10월 5일 작업 미션:  EDA Final Report 완성 및 리뷰

- [x]  Splint Day 5 : 3. 팀원 컨디션 및 특이 사항 확인

**Comment by seungjaepack** [comment]
-대가설 정리하기
대가설 1 -> 대가설 2 (+연령대별 코로나) -> 대가설 3 (+연령대별 상품군, 온라인, 모바일)  -> 대가설 4 (연령대 별 조회수)

- 대가설 1
 코로나 확진자수 X 상품군 카테코리별 거래액 (온라인+모바일)
- 대가설 2
 **연령대별** 코로나 확진자수 x 상품군 카테코리별 거래액 (온라인+모바일)
- 대가설 3
연령대별 코로나 확진자수 x **연령대별** 상품군 카테코리별 거래액 **(온라인, 모바일)**
- 대가설 4
 연령대별 코로나 확진자수 x **연령대별 상품군 카테고리별 조회수** (온라인, 모바일)

**Comment by seungjaepack** [comment]
- 벤다이어 그램으로 대가설 정리하기
