### ISSUE TITLE
10/03 Sprint Day 6: To-Do-List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#11]
# Sprint Day 6 JOB Split : 
- [x] 노션에 팀 프로젝트 공간 생성
- 커버 생성, 팀 페이지 꾸미기
- 섹션을 4구획(EDA, Team Menage, Source, Reference) 생성하기
- 섹션 별 Teamplate 만들기
- Team Menage 섹션 작성하기 (Sprint Day 1 ~ Day 6)

- [x] Code_Crawling 정리하기 
- 1. Naver API Crawling 코드 정리 -> Notion에 update
- 2. Selenium Crawling  ->  Notion에 update

- [x] Data modeling 부분 정리하기
- 1. Mobile outlier 시각화 자료 및 커맨트 정리하기

- [x] 중간 자료 정리 (DB Source) : Git add --all & commit
- [x] 프로젝트 보고서 Intro 작성 하기
- 인포그래픽을 이용하여 Intro page 작성해보기
- [x] 셀레니움을 통한 크롤링을 통해 인사이트 도출 토대 마련하기
- 특정 피처 카테고리의 인기검색어 500개 가져오기
- [x] 워드 클라우드 필요 모듈 설치하기
- [x] 워드 클라우드 설치 이슈 해결하기
   1. Konlpy import 이슈 1~3 해결하기
   2. Jpype1 version 이슈 1 해결하기
   3. Wordcloud font 이슈 해결하기

# Sprint Day 6 Goal : 
- Data 수집(Selenium), Challenge 개인 과제 진행해보기, Splint Day 7 작업 환경 조성하기(노션 팀 페이지 생성 및 작성 가능하게 구성)
