### ISSUE TITLE
10/04 Sprint Day 7 : To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#12]
# Sprint Day 6 Review(AM 9:00 ~ AM 9:15) :

- [x] Review 1 : Main Tasks

 - Checking Sprint Day 6 tasks done list  : Crawling part, Visualization(wordcloud)
 - Checking each part processing status
   1. Pre-processing Data : 주요 수치 정리한 테이블 정리 상태
   2. Modeling : 가설 별 남은 작업 정리 상태

- [x] Review 2 : Managing Source

- Source (code) 
  1. Crawling and Visualization(word cloud) Part 
     - Naver selenium part 정리 완료(Notion에 업데이트)
     - 예시) 남은 작업
     - a)  Naver api code 정리 (refactoring)
     - b)  Word Cloud code 정리 (refactoring)
  2. Checking Pre-processing Data Part :
  3. Checking Modeling Part :
   

- [x] Review 3 : Checking Condition last week and today

 
 

------------------------------------------------------------------------------------------------------------------------------------------
# Sprint Day 7 JOB Split :

- [x] 1. 팀 노션 페이지 소개 및 사용 환경 구축 및 교육 (AM 9:15~ AM 9:50)
- [x] 2. 각 파트별 남은 작업 각 이슈에 정리하기 (AM 10 :00 ~ AM10: 20) : 작업 시간 (10시 30분 ~ 19시) 4part로 나눠서 계획
- [x] 3. 각 파트별 남은 작업 하기 (AM 10 :30 ~ AM 11 :40) : 작업 Part 1
- [x] 4. 각 파트별 남은 작업 하기 (AM 11 :40 ~ AM 11 :50) : 작업 Part 1 review
- [x] 5. 각 파트별 남은 작업 하기 (PM 1 :00 ~ PM 2 :20) : 작업 Part 2
- [x] 6. 각 파트별 남은 작업 하기 (PM 2 :20 ~ PM 3 :00) : 작업 Part 2 review and intermission
- [x] 7. 각 파트별 남은 작업 하기 (PM 3 :00 ~ PM 4 :20) : 작업 Part 3
- [x] 8. 각 파트별 남은 작업 하기 (PM 4 :20 ~ PM 04 :35) : 작업 Part 3 review
- [x] 9. 각 파트별 남은 작업 하기 (PM 04 :35 ~ PM 06 :30) : 작업 Part 4
- [x] 10. 각 파트별 남은 작업 하기 (PM 6 :30 ~ PM 7 :00) : 작업 Part 4 review and Presentation

# Sprint Day 7 Goal :
- [x]  1. 노션 협업 환경 각 팀원 구축 완료 및 교육
- [x]  2.  EDA 각 파트별 소스 정리 업무 분장
- [x]  3. 각 파트별 1차 발표 리허설

**Comment by seungjaepack** [comment]
20211004 작업 세분화 리스트

- [x] Part 1. 노션 템플렛 보완
- [x] Part 2. 코드 정리 (셀레니움, 워드 클라우드)
- [x] Part 3. 가설 파트 정리
- [x] Part 4. 자료 수집 파트 정리
