### ISSUE TITLE
10/05 Sprint Day 8 : To-do-list 

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#13]
# Sprint Day 7 Review :

- [x] Review 1 : Main Tasks

 - Checking Sprint Day 7 tasks done list  : 문제정의, 데이터 수집, 데이터 탐색, 데이터 전처리, 모델링
 - Checking each part processing status

- [x] Review 2 : Managing Source   

- [x] Review 3 : Checking Condition last week and today

------------------------------------------------------------------------------------------------------------------------------------------
# Sprint Day 8 JOB Split :

- [x] 가설 설정 다듬기 (가설 1, 서브가설 3)
- [x] 모델링 마무리하기
- [x] 모델링 평가 마무리하기
- [x] 결과 보고서 작성하기
- [x]  아이데이션 문서 작성
- [x] 전체 페이지에서 내용 보충하기
- [x]  EDA 소스 정리하기
- [x]  전체 편집하기
- [x]  발표 준비하기

# Sprint Day 8 Goal :
- [x]  1. EDA 보고서 작성 마무리
- [x]  2.  EDA 발표 준비
- [x]  3. 각 파트별 1차 발표 리허설
