### ISSUE TITLE
10/06 Sprint Day 9 : To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#14]
# Sprint Day 8 Review :

- [x] Review 1 : Main Tasks

 - Checking Sprint Day 8 tasks done list  : 결론
 - Checking finally each part processing status

- [x] Review 2 : Uploading Source   

- [x] Review 3 : Checking Condition last week and today

------------------------------------------------------------------------------------------------------------------------------------------
# Sprint Day 9 JOB Split :

- [x] 1. 아이데이션 문서 작성
- [x] 2. 노션 보충 부분 작성
 1. 코드 섹션 편집
 -  편집 방법 : 5. 데이터 탐색  (outlier,잔차 계산, 데이터 분포, 그래프 추이 패턴, 상관 관계 확인) 순으로 코드 설명 재배치
 -  해당 부분 : Processing Data, Modeling
 
 2. Reference 파트
 - 인용하거나 참고한 URL 채우기
  
- [x] 3. 소스 업로드 (Temp google drive -> SSAC Google Drive- >Git (develop -> main merge)
- [x] 4. 발표 준비

# Sprint Day 8 Goal :
- [x]  1.  EDA 토이 프로젝트 발표 
- [x]   2. 토이 프로젝트 발표 피드백 정리
- [x]  3.  토이 프로젝트 마무리와 향후 계획
