### ISSUE TITLE
210929 Sprint Day2 : To-Do-List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#3]
- [x] R&R 정하기
- 1. 스크럼 마스터, 데이터 수집, 각 단계에서 이슈 해결, 문서 작성(회의록, 프로젝트 하이라이트 문서, 프로젝트 헌장) git 운영(데이터 관리, 백업), 코드 템플렛 작성(네이버 API 연동 모듈, EDA 클래스 모듈) 자료 탐색(각 단계 별 필요 라이브러리 탐색(시각화 라이브러리, API 라이브러리))
- 2. 데이터 처리 (변수 생성, 지정, 데이터 프레임 생성), 모델링(시각화, 데이터 통계적 처리), 문서 정리(영문화)
- 3. 데이터 수집 및 처리 (데이터 전처리, 코드 관리) 와 인사이트 도출(경영학적 접근), 문서 관리
- [x] 팀장 정하기
- [x] 단위 프로젝트 운영 방식 정하기
- 스프린트 단위는 1일~ 1.5일
- [x] Ground Rule 정하기
1. 팀원 간 작업 진행 내용 파악 (중복 작업 피함, 병목 체크, 공동으로 처리할 이슈 확인)
- R&R을 프로젝트 작업을 세분화 하여 이슈 단위로 관리 (Daily plan & Report time setting)
- 리포팅 방식 : 현재 상태, 확인 내용, 이슈 내용, 공동 이슈 레이즈 
2. 온라인 미팅 시 규칙
3. 회의록 작성
- [x] 작업 관리 운영 방식
 1. 자료 업로드 폴더 구분 : DOC, CODE, DB, MODELING
 2. 백업 : Cold Physical backup, Hot Logical Backup 

- [x] 프로젝트 타이틀 정하기

- [x] 프로젝트 개요 문서 작성하기 (방향, 수집 방식, 결과 전망,도전적인 과제)
  - 도전적인 과제: new Visualization Library 사용하여 그래프 작성, 인포그래픽 자료 삽입하기

- [x] 아이데이션 문서 작성

**Comment by seungjaepack** [comment]
1. 프로젝트 가이드 라인
 - 프로젝트 수행 목적, 동기
 - 사용할 데이터의 변수 설명 (수집경로, 단위)
 - 샘플링 수 (10,000개 샘플 사용)
 - 모델 선택 및 최적화 과정 포함
 - 솔루션 제공 및 문제점 도출  항목

**Comment by seungjaepack** [comment]
1. 프로젝트 초안 작성하기

**Comment by seungjaepack** [comment]
1. 트랜드 경향 리포트를 확인하여 범주형 변수, 수치형 변수를 나눠보고 확장할 인사이트(사회적 이슈 : 고령화, 코로나, 카테고리별 트랜드 경향성과 연계)을 생각해 보기

**Comment by seungjaepack** [comment]
1. 아이데이션 문서 작성하기
 - 프로젝트 주제(검증 목표) :  코로나 상황 이전/이후 상품 군 별 온라인 쇼핑 거래액을 통해 쇼핑 동향을 파악 (2017~2021)
 - 데이터 수집을 위한 참고 사이트 : 데이터 포털 data set(xls) 또는 데이터랩 API를 통한 데이터 수집
 - 수집 가능 : 수집 가능 
 - 데이터 수집/추출 방안
 - 데이터 분석 방향 및 아이디어 : 상관관계 분석, 정량적 분석, 정성적 분석 
 - 예상되는 어려움

**Comment by dahee-diana96** [comment]
다른 참고해볼만한 데이터셋 사이트들을 찾아보았습니다. 말씀해주신 사회적 이슈와 관련하여 찾아봐도 좋을 듯 하여 공유드립니다.
- [kaggle] https://www.kaggle.com/datasets
    - 가입 필요. 흥미로운 주제의 데이터가 많이 보임. But 모든 데이터들이 정확하단 보증은 없음
- [DataWorld] https://data.world/
    - 가입 필요.  다양한 데이터들이 있긴 한데, kaggle처럼 마냥 데이터들이 정확하단 보증이 없는 듯 해보임.
- [UCI Dataset] https://archive.ics.uci.edu/ml/datasets.php
    - 연구 목적을 위한 데이터들 위주. But 좀 올드한 부분이 있고, 마냥 다양하진 않은 감이 있음

**Comment by seungjaepack** [comment]
1. 코로나 발생 이전과 이후를 기점으로 온라인 /모바일 소비 성향 분석
2. 온라인/오프라인 소비 비교 : 통계적 분석, 가설 설정 및 검증

**Comment by seungjaepack** [comment]
Additional JOB
 - 다희님: 적용할 데이터 분석 기법 확인 
- 태양님: SWOT 분석을 주제에 접근 가능한지 확인

**Comment by seungjaepack** [comment]
09/29 Daily plan
- 아이데이션 문서 작성 : 작성 완료
- GIT 폴더 생성 및  Data fetch 환경 설정 : 태양님 셋팅 완료, 다희님 9/30일날 진행
- 프로젝트 초안 문서 작성 : 작성중
- 네이버 API 연동 방법 확인 : API 방법 서치중
