### ISSUE TITLE
210930 Sprint Day3 To-Do List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#7]
- [x]  Sprint Day 2 Review 
- Review1
   - 1. 3월 (2020,2019) 카테고리별 거래액 그래프 확인
   - 2. 코비드 발생 이전 /이후 카테고리별 거래액 그래프 확인
   - 3. 코비드 일자별 / 월별 데이터 확인
- Review 2
  - Check Sprint system  : 이슈 레포트, 스프린트 작업 상태 확인
- Reveiw 3
-  Source 관리 : 코드, 모델링 관리, 각 소스에 대한 피드백 커맨트 이력 관리
---------------------------------------------------------------------------------------------------------------------------------------------
- [x]  Setting Sprint Day Goal :  상관 관계 (코비드, 카테고리별  거래액), 통계 기법 설정, 인덱스 수치 확인하기

- [x]  Daily job Split
- 1. 코비드 월별 데이터 시각화
- 2. 코비드 월별 데이터와 카테고리별 거래액 데이터의 feature 간 상관관계 확인 :
    Step 1 :  Heatmap ->  상관관계 확인 -> cor 1.0~0.5 feature 추출 
    Step 2:   Pair-Plot 확인
    Step 3:   Specific Plot
    Step 4:  통계적 기법 적용, index 추출
    Step 5:  Index Plot 
- 3. 코로나 이전/이후 시기 쇼핑 트랜드 확인 베스트 3 or 5 확인함으로써 사회 현상에 따른 트랜드의 변화를 파악

- [x] checking status each Part : Data Processing, Modeling
- [x] 문서 작업 목록 리스트 작성
 -  1. 아이데이션 문서 작성 
 -  2. 변수 테이블 작성
 -  3. 작업 기록 템플렛 작성
- [x]  Git 작업
- 1. git flow setting : 다희님  / 태양님 (완료)
- 2. 각 폴더에 자료 정리

- [x]  작업 기록 및 Final Report 문서 작성에 대해 생각해 보기
- 1. template 구상
- 2. 작업 기록 장소 구상

**Comment by seungjaepack** [comment]
- Git : git flow setting : 다희님 (완료)
- Naver API 연동 (완료)
- Naver를 통한 데이터 추출 (출산/ 육아, PC, 10~60세 이상 조회수) 완료
- 아이데이션 가설 설정 추가 완료
