### ISSUE TITLE
10-01 Sprint Day 4 To-Do-List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/Toy_Project_EDA#8]
- [x]  Sprint Day 3 Review

- Review1
1. 연령대 별 코로나 확진자수와 카테고리별 거래액 상관 관계 
2. 시각화  리뷰 정리
3. 온라인 /모바일 시각화 

- Review 2
Check Sprint system : 이슈 레포트, 스프린트 작업 상태 확인

- Reveiw 3
Source 정리 : 코드, 모델링 관리, 각 소스에 대한 피드백 커맨트 이력 관리

---------------------------------------------------------------------------------------------------------------------------------
 

- [x] #9

 1. 중간 정리 (소스 코드, 모델링 자료, 커맨트 취합, 샘플수 확인)
 2.  남은 작업 확인하여 계획하기
 3.  각 파트 별 코드 공유
 4.  조회수 데이터셋 생성 및 전처리 및 일부 시각화

- [x]  Daily job Split

1. 모델링 코드 및 시각화 데이터 정리 -> 공유 -> 각 소스의 추가 커맨트 하기
2. 카테고리별 분류 테이블 정리 (네이버 조회수 카테고리, 거래액 카테고리) -> 네이버 카테고리별  Cat_id 번호 열로 추가
3. 조회수 데이테 전처리 ->  시각화(시각화 우선순위 정해서 우선순위별로 먼저 진행)

- [x]  문서 작업 목록 리스트 작성해보기
 1. 프로젝트 진행 과정 기록 문서 작성
 2. 프로젝트 결과 프리젠테이션 문서 작성
- [x]  가설 설정 정리 및 추가 가설 설정 하기
- [x]  Git  reposit에 소스 정리 방식 논의하기

- [x] 팀원 컨디션과 특이 사항 확인 : 
   - 주말 팀작업 가용 일정 확인
    - 1. 김다희: 10/2 (토요일)  오후 가능 , 10/4 (월요일) 오전 9시 ~ 오후 7시 전까지 가능
    - 2. 심태양, 백승재: 10/2일(토요일) 오후 가능, 10월 3일 ~ 4일 가능
    - 특이 사항 : 
    - 1. 백신 접종 예정 (10월 2일 오전 11시) : 백승재, 건강상태 이상시 팀원에게 전달 예정

**Comment by seungjaepack** [comment]
1.  데이터 셋과 총 샘플수(row기준) 확인
 1) 상품 카테고리별 거래액 Data set (모바일, 온라인, 총계, 2017.01 ~ 2021.07):  row 165  (55 x3)
 2) 연령대별 코로나 Data set (2020.1.20 ~ 2021.9.29) row 619 
 3) 연령대별 특정 상품 카테고리별 조회수 (연령대 1 / 카테고리 1) 2020.3.01. ~ 2021.7.31 data frame 1개 (517rows))
 - 연령대 6개
 - 상관 관계 높은(거래액, 코로나) 카테고리 8개 - >517 x 6 x 8 = 24,816 row 
 4) 총 합계  total : 25,600 (rows)

**Comment by seungjaepack** [comment]
1. 강사님 문의 내용 정리 : 가설을 통한 인사이트로 부터 전망을 예측할 수 있는 통계적 기법 문의
- 목적 : 향후 전망을 확인하여 특정 집단과 특정 카테고리 간 상관관계가 높은 상품군을 뽑아서 타켓 프로덕트 리스트를 만들기
 - 코로나 시대가 지속되는 시기에 향후 특정 카테고리의 거래액 전망 (연령대별 분리가 가능하여 전망할 수 있는지)
 -참고 :  프로젝트 단계적 접근 방향
가설 1. 코로나 상황과 상품군 카테고리별 거래액 상관 관계 
-> 코로나 상황과 상품군 카테고리별 
가설 2. 연령대별 코로나 확진자 수와 온라인과 모바일 쇼핑의 거래액 상관 관계
   -> 상위 5개의 산업군들: 음식 서비스, 가전-전자-통신기기, 애완용품, 아동-유아용품, 음식료품 (모바일)
  ->  하위 5개의 산업군들: 기타, 여행 및 교통서비스, 문화 및 레저서비스, 신발, 의복 (모바일)
가설 3. 연령대별 코로나 확진자 수와 카테고리별 거래액 상관관계
 ->
가설 4. 상품군별 거래액과 특정 상품군 조회수의 상관 관계 
-> 상관 관계가 높은 특정 연령대와 특정 상품군을 확인 -> 코로나가 지속 -> 향후 전망 확인 0> 이커머스에 타겟팅할 특정 집단확인

**Comment by seungjaepack** [comment]
강사님 피드백 1: 통계적 기법을 통한 전망 예측
-> 전망치 예측보단 현재 분석한 상관관계에서 음의 관계도 확인해서 인사이트를 도출 시켜 볼 것

**Comment by seungjaepack** [comment]
강사님 피드백 2 :  데이터 셋과 총 샘플수(row기준) 산정 기준 내용 반영 최종 정리 내용
-> EDA 샘플 기준 가이드는 일반적인 경우 10,000개이고,  Date가 row인 경우에는 3년 ~5년 데이터 정도가 적합한 것으로 확인받음(강사님 피드백 사항)
-> 최종 Total sample 수 : 1368개 샘플 수로 EDA 진행
-  참고 사항: 
1. 연령대별 특정 상품 카테고리별 조회수의 Date Row로 Sample 수 count (일단위, 2018. 01 ~ 2021.09.29) :  1368 rows(Date) 
2. 상품 카테고리별 거래액 Data set (월단위, 2017.01 ~ 2021.07): 55 rows (month)
3. 연령대별 코로나 Data set (일단위, 2020.1.20 ~ 2021.9.29) : 619 rows(date)

**Comment by seungjaepack** [comment]
강사님 피드백 3: 코로나 시점을 기준으로 하여 상대적인 조회 비율(ratio)을 조회수로 생각 할 수 있음
- 상대적인 조회 비율은 ((1Date 조회수 / 전체 조회수) x100)임

**Comment by seungjaepack** [comment]
- 중간 정리 : 설정한 가설을 기준으로 커맨트, 남은 작업 정리
 - 대가설 1:  코로나 시대에 사람들의 이커머스 (온라인, 모바일) 소비 패턴에 변화가 있을 것이다.
    - **검증 확인**: **월별 코로나 확진자 수**와 상품군 카테고리별 거래액 상관 관계
         - 작업 내용 :
         1. 코로나 기준일(2020.03.01)으로 하여 상품군 별 증가액, 증감액 확인 (모바일 쇼핑)
         2. 카테고리별 거래액 (월별 합계)에 대한 인터넷과 모바일 쇼핑 간의 거래액 비교 (2017.01~ 2021.07)  
         - 체크 :  코로나 기준일로 인터넷과 모바일 쇼핑 간의 거래액 변경 필요 
         3-1. 히트맵 분석 (모바일 쇼핑데이터 X 확진자수(국내+해외) 상관 관계 분석
         -> 온라인도 추가 시각화하여 정리 필요
         3-2.
         -> 상위 5개의 산업군들: 음식 서비스, 가전-전자-통신기기, 애완용품, 아동-유아용품, 음식료품 (모바일)
         -> 하위 5개의 산업군들: 기타, 여행 및 교통서비스, 문화 및 레저서비스, 신발, 의복 (모바일)
         - 남은 작업 : 코로나 온라인 
 
 - 대가설2 :  코로나 시대에 특정 연령대의 확진자 수는 해당 연령대에 영향을 미칠 것이고 특정 상품군에 대한 거래가 발생할 것이다.
    - **검증 확인** **:연령대별** 코로나 확진자 수와 온라인과 모바일 쇼핑의 거래액 상관 관계
         -> 상관 관계가 있는 연령대를 확인하기
         -> 해당 연령대의 모바일과 온라인 카테고리별 상품군 거래액 비교


 - 대가설3:  코로나 시대에 특정 연령대의 확진자 수는 해당 연령대에 영향을 미칠 것이고 특정 상품군에 대한 온라인/ 모바일  
조회로 이뤄질 것이다.
      - **검증 확인** :연령대별 코로나 확진자 수와 카테고리별 거래액 상관 관계 확인하기
 
 - 대가설 4: 코로나 시대에 특정 연령대의 확진자 수는 해당 연령대에 영향을 미쳐서 특정 상품 군에 대한  조회가 구매로 이어질 것이다. 
    - **검증 확인** :연령별 확진 자수와 과 연령별 특정 상품군 조회수의 상관 관계 관계 확인하기
    - 대가설 2번과 비교하여 조회가 구매로 이뤄지는지 확인하기

**Comment by seungjaepack** [comment]
- Git, Google  Drive folder 정리 작업 완료

**Comment by seungjaepack** [comment]
- 가설 1 옵션 추가 제안 생각해 보기  : 거리 두기 단계에 따라 지역 분리해야 되기 때문에 지역별로 거래액이 구분된 테이블과 상관관계를 확인하기에는 제한이 있음을 확인하였음

**Comment by seungjaepack** [comment]
- Naver Api 이용 데이터 수집 : 온라인_식품, 출산/육아, 가전 완료~!

**Comment by seungjaepack** [comment]
작업 세분화 내용
1) 다희님:
- 코드 자료 섹션 분리 (위에 가설 정리 내용 복사 붙여서 각 항목에 그래프 배치하기)
- 온라인 40~60대의 상품 피처 뽑아낸 이유를 그래프에 음영처리와 커맨트 달기-> 3번에서 4번으로 접근한 근거를 명시하기 위함
2) 태양님:
- 데이터 전처리한 순서대로 다희님과 시각화하여 해당 피처(양/음의 상관관계)가 조회수랑도 상관관계가 있는지 확인하기 -> 현재 조회수가 누적치로 되있는데 처리결과가 이상하면 평균치로 바꿔서 시각화 해보기
 - (온라인 10~60대, 식품, 사무용품, 문화, 여행) 데이터 전처리하기

**Comment by seungjaepack** [comment]
Naver Api 이용 데이터 수집 : 모바일, 온라인 (디지털가전, 문화공연, 사무용품, 식품, 여행, 출산육아) 완료~!

**Comment by seungjaepack** [comment]
1. 문화/공연에 온라인 조회수 결측치 확인 (10대, 60대) : 반복해서 Naver API 를 이용하여 데이터를 수집하였지만 11개 데이터가 row가 없음
-> 결측값 처리 방법 중 비조건부 평균 대치법(Mean Imputation)을 적용하여 결측치 처리함

**Comment by taeyang1224** [comment]
문화/공연 온라인 조회수 결측치 확인 결과
- 10대 : 2020-05-27, 2020-07-05, 2020-07-09, 2020-08-30, 2020-09-05, 2020-09-08, 2020-10-02, 21-01-05 (총 8개 확인)
- 60대 : 2020-04-11, 2020-06-13, 2020-07-01, 2020-07-05, 2020-08-23, 2020-08-30, 2020-09-05, 2020-09-19, 2020-12-30, 2021-01-01, 2021-01-11(총 11개 확인)
